version: '3'

services:
   mysql:
     image: mysql:8
     volumes:
       - ./mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASS}

   wordpress:
     depends_on:
       - mysql
     build:
       context: ./
       dockerfile: wordpress.dockerfile
     volumes:
      - ./html:/var/www/html
     ports:
       - ${SERVE_PORT}:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: ${DB_USER}
       WORDPRESS_DB_PASSWORD: ${DB_PASS}
